version: '3'
services:
  node:
    build: ./
    working_dir: '/packages'
    tty: true
    env_file: ./.env
    environment: 
      TZ: Asia/Tokyo
    privileged: true
    volumes:
      - ./:/packages